下面的示例展示了两个矩阵相加的情况。

$\begin{bmatrix}
  1. & 1. & 1. \\
  1. & 1. & 1. \\
\end{bmatrix} +
\begin{bmatrix}
  1. & 2. & 3. \\
  4. & 5. & 6. \\
\end{bmatrix} =
\begin{bmatrix}
  2. & 3. & 4. \\
  5. & 6. & 7. \\
\end{bmatrix}$

In [5]:
import tensorflow as tf
import numpy as np

with tf.Session():
    input1 = tf.constant(1.0, shape=[2, 3])
    input2 = tf.constant(np.reshape(np.arange(1.0, 7.0, dtype=np.float32), (2, 3)))
    output = tf.add(input1, input2)
    print(output)
    result = output.eval()

result

Tensor("Add_2:0", shape=(2, 3), dtype=float32)


array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.]], dtype=float32)

In [6]:
# 查看GPU
device_name = tf.test.gpu_device_name()
print(device_name)
if device_name != '/device:GPU:0':
    raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

/gpu:0


SystemError: GPU device not found

In [4]:
# hello world
c = tf.constant('hello world!')
with tf.Session() as sess:
    print(sess.run(c))

b'hello world!'


TensorFlow 提供了一个默认图。不过，建议创建自己的 Graph，以便跟踪状态（例如，你可能希望在每个单元格中使用一个不同的 Graph）。

In [9]:
g = tf.Graph()

with g.as_default():
    x = tf.constant(8, name='x_const')
    y = tf.constant(2, name='y_const')
    sum = tf.add(x, y, name='x_y_sum')
    
    with tf.Session() as sess:
        print(sum.eval())

10


In [11]:
x = tf.constant(8, name='x_const')
y = tf.constant(2, name='y_const')
sum = tf.add(x, y, name='x_y_sum')

with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    #print(sum.eval())
    print(sess.run(sum))

10


In [7]:
# 广播 
import tensorflow as tf
g = tf.Graph()

with g.as_default():
    primes = tf.constant([[2, 3, 4], [5, 6, 7]], dtype=tf.int32)
    ones = tf.constant([[2],[3]], dtype=tf.int32)
    just_beyond_primes = tf.add(primes, ones)
    
    with tf.Session() as sess:
        print(just_beyond_primes.eval())

[[ 4  5  6]
 [ 8  9 10]]


In [9]:
# 张量变形
with tf.Graph().as_default():
    matrix = tf.constant([[1,2], [3,4], [5,6], [7,8],
                    [9,10], [11,12], [13, 14], [15,16]])
    reshaped_2x8_matrix = tf.reshape(matrix, [2,8])
    reshaped_4x4_matrix = tf.reshape(matrix, [4,4])
    with tf.Session() as sess:
        print("Original matrix (8x2):")
        print(matrix.eval())
        print("Reshaped matrix (2x8):")
        print(reshaped_2x8_matrix.eval())
        print("Reshaped matrix (4x4):")
        print(reshaped_4x4_matrix.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped matrix (2x8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Reshaped matrix (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
g = tf.Graph()
with g.as_default(), tf.Session() as sess:
    v = tf.Variable([3])
    w = tf.Variable(tf.random_normal([1], mean=1.0, stddev=0.35))

TensorFlow 的一个特性是**变量初始化不是自动进行的**。例如，以下代码块会导致错误：

In [16]:
with g.as_default(), tf.Session() as sess:
    try:
        v.eval()
    except tf.errors.FailedPreconditionError as e:
        print("Caught expected error: ", e)

Caught expected error:  Attempting to use uninitialized value Variable
	 [[Node: _send_Variable_0 = _Send[T=DT_INT32, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=4026675870366599110, tensor_name="Variable:0", _device="/job:localhost/replica:0/task:0/cpu:0"](Variable)]]
